In [1]:
pip install google-play-scraper

Requirement already satisfied: google-play-scraper in /usr/local/lib/python3.12/dist-packages (1.2.7)

In [2]:
from google_play_scraper import app

result = app(
    'mam.reader.ipusnas',
    lang='en',
    country='us'
)

print(f"App: {result['title']}")
print(f"Rating: {result['score']}")
print(f"Downloads: {result['installs']}")
print(f"Price: {result['free']}")

App: iPusnas
Rating: 3.5714285
Downloads: 1,000,000+
Price: True

In [3]:
from google_play_scraper import reviews, Sort

result, continuation_token = reviews(
    'mam.reader.ipusnas',
    lang='en',
    country='us',
    sort=Sort.NEWEST,
    count=4000
)
for review in result:
  print(f"{review['userName']}: {review['score']} stars")
  print(f"Review: {review['content']}")
  print(f"Date: {review['at']}")

A Google user: 4 stars
Review: novel lockwood and co nya lengkapin plissss
Date: 2026-06-26 01:19:13
A Google user: 1 stars
Review: tidak bisa membuka buku yang sudah dipinjam, tertulis bisa di baca, tapi ketika di klik tidak bisa memuat ke halaman buku, padahal saya sudah menggunakan aplikasi resmi, dan tidak ada modifikasi apapun, tolong diperbaiki maslaah ini, apakah ini bug, gangguan atau semacamnya yang jelas tolong diperbaiki.
Date: 2026-06-25 08:05:43
A Google user: 1 stars
Review: Kenapa saya tidak bisa membaca buku yang sudah saya pinjam tiba-tiba setelah melakukan login di laptop? Saya tidak bisa membaca buku di laptop dan ketika akan membaca di perangkat hp ada pop up kalau tidak bisa memuat karena tidak dapat memverifikasi perangkat. Mohon jawabannya... padahal kmrn sore masih bisa, ini tiba-tiba trouble. Terus setelah lihat review lain juga banyak masalah serupa. Tolong ini bagaimana?
Date: 2026-06-25 07:43:20
A Google user: 2 stars
Review: Tolong dibenerin lagi apk nya karena saya mau baca jadi gabisa, suruh download di play store padahal emang downloadnya di play store
Date: 2026-06-25 07:34:18
A Google user: 1 stars
Review: Tidak mampu memverifikasi perangkat.
Date: 2026-06-25 06:21:29
A Google user: 1 stars
Review: helloooo there are people using this app to read books so they can fulfill one of their 75 Hard Challenge tasks, which is reading 10 pages of something non-fiction. you have some good collections there. the challenge is already hard, don't make it harder. fix your app, please. I'm already using the real app here from Play Store. nvm, I'm using iJakarta now
Date: 2026-06-25 05:40:19
A Google user: 3 stars
Review: saya tidak bisa baca. padahal 2hari yang lalu lancar aplikasinya buat baca. kenapa ya?
Date: 2026-06-25 04:31:55
A Google user: 1 stars
Review: sering error, buku ga lengkap
Date: 2026-06-25 04:00:42
A Google user: 3 stars
Review: Aplikasinya bagus banget, koleksinya banyak, dan banyak buku populernya. Sayangnya aplikasinya sering error. Kadang data gak terverifikasi, logout sendiri, buku gak bisa dibuka, dan lain-lain. Semoga semakin upgrade semakin bagus lagi apk nya.
Date: 2026-06-24 12:31:15
A Google user: 3 stars
Review: apk buat menunjang kecerdasan anak bangsa nggak proper banget. Tolong di update lebih proper lagi.
Date: 2026-06-24 01:20:56
A Google user: 2 stars
Review: aslinya bagus, tp sering bgt error. thanks.
Date: 2026-06-23 11:58:11
A Google user: 5 stars
Review: ANJAY BARU TAU ADA PERPUM ONLINE, KOK GADA YANG NGASIH TAU BZIRRRR. overal okeeey, cmn ngantrinya luamaaaaaaaaaaa. tomlong dungs fix bugnya, suka eror bagian berandanya jd kosong gitu. pls yaaaa ^^
Date: 2026-06-23 11:20:28
A Google user: 1 stars
Review: turunkan harga buku
Date: 2026-06-22 15:25:58
A Google user: 5 stars
Review: Sedih bgt, untuk android 9 users udah ga bisa pake apk ini lagi. Padahal lagi asyik baca satu buku. Berharap masih bisa pakai karena belum bisa beli hape baru. Huhu, harus beli e-book di play book jadinya. Padahal ipusnas beneran banyak ngebantu banget, buat pinjam banyak buku secara online dan gratis itu ngebantu bgt loh daripada beli buku bajakan.
Date: 2026-06-22 14:15:31
A Google user: 1 stars
Review: padahal app dari pemerintah tapi kinerjanya buruk banget, ngk bisa baca buku yg dipinjam dengan alasan konyol
Date: 2026-06-19 11:33:01
A Google user: 1 stars
Review: beberapa tahun lalu, saya menggunakan app ni dengan baik. hari ini saya update, malah tidak bisa terbuka. jadi coba uninstaal kemudian install lagi. sudah login, muncul notif tentang koneksi padahal saya sudah terhubung dengan wifi. pakai kuotapun, masih tidak bisa digunakan untuk mencari buku
Date: 2026-06-18 00:11:30
A Google user: 2 stars
Review: bandwith nya gedein. susah loginnya -_
Date: 2026-06-17 15:17:00
A Google user: 1 stars
Review: Loading lama betul, gak bisa daftar akun. Padahal sinyal bagus, memakai wifi. Loading terus pas ngisi bagian kecamatan. dan mau memasukkan akun google.
Date: 2026-06-16 02:09:53
A Google user: 1 stars
Review: Tidak bisa meminjam buku padahal sudah bolak-balik nyoba install ulang 👎
Date: 2026-06-13 07:39:17
A Google user: 1 stars
Review: pertanyaanku, klo verifikasi perangkat gagal tuh harus ngapain? install uninstall juga gabisa. yg salah tuh siapa? yg gagal verifikasi siapa? situsmu atau perangkatku?
Date: 2026-06-11 01:40:24
A Google user: 1 stars
Review: mbg mau buku gratis
Date: 2026-06-10 04:16:42
A Google user: 1 stars
Review: semakin hari semakin parah 😭
Date: 2026-06-10 01:56:17
A Google user: 1 stars
Review: bodoh bgt lemot bikin emosi error trs
Date: 2026-06-10 01:15:29
A Google user: 4 stars
Review: update an baru tapi sepertinya ada kendala sehingga tidak bisa meminjam bukunya
Date: 2026-06-07 12:31:53
A Google user: 5 stars
Review: bisaa dipake lagii, loveee🤭💕
Date: 2026-06-05 07:40:03
A Google user: 4 stars
Review: Buku cukup lengkap, hanya saja kadang ada bug yang mengganggu (ex. bug gak bisa pinjam buku, dll)... Semoga kedepannya lebih baik & koleksi bukunya lebih banyak lagi
Date: 2026-06-04 13:24:21
A Google user: 1 stars
Review: It sucks that it's not compatible on Pad alias app freeze di Pad padahal mau baca dengan layar yang lebih gede.
Date: 2026-06-03 21:50:32
A Google user: 5 stars
Review: Aplikasinya sangat berguna bagi pembaca yang tidak terlalu mampu membeli 1 buku dalam sebulan. Walaupun sering error, aku berpikiran untuk memberi rating bintang 5. Semoga aplikasi ini bisa semakin wort it.
Date: 2026-06-03 07:15:34
A Google user: 1 stars
Review: error apa gimana sihh, katanya my device verification is failed??? already reinstalled and do whatever i can, but the problem stay still?? i even log onto new account but the page went blank, what is going on? this is getting pretty annoying :/ couldnt even login on the website bruh ughh whats the problemmmm, my network is going pretty good, my storage is still wide, my device is certified, what else does it need
Date: 2026-06-03 05:03:38
A Google user: 1 stars
Review: mengapa selalu buffering? sinyal saya stabil padahal.
Date: 2026-06-02 23:43:03
A Google user: 1 stars
Review: pas mau pinjam atau baca selalu diblg apk modifikasi pdhl downloadnya di playstore huhhhh aneh
Date: 2026-06-02 17:39:10
A Google user: 5 stars
Review: Makasih buat kakak-kakak yang buat aplikasi ipusnas karena dari aplikasi ini aku bisa pinjam buku yang ngga bisa aku dapetin. memang ada beberapa kendala saat pinjam buku tapi di coba berkala buat login logout akhirnya bisa lagi. Walaupun ada beberapa kekurangan semoga tetep bisa menjadi bahan perbaikan kedepannya.
Date: 2026-05-31 07:43:15
A Google user: 1 stars
Review: ngga bisa pinjam buku karena error di verifikasi, tolong diperbaiki yah tks
Date: 2026-05-31 06:30:13
A Google user: 5 stars
Review: Tetiba hari ini semua device ngga bisa akses baca, katanya verifikasi perangkat gagal. Bug nya baru lagi ni. seharian jadi ngga baca buku
Date: 2026-05-30 14:39:52
A Google user: 1 stars
Review: Aplikasi jelek. Unnist karena gabisa login, mau reinstall malah gabisa karena ga kompatibel.
Date: 2026-05-29 13:10:11
A Google user: 1 stars
Review: pastikan pakai aplikasi resmi? kurang resmi apalagi ini? haduh
Date: 2026-05-28 22:43:51
A Google user: 1 stars
Review: Tolong segera perbaiki aplikasi karena setiap akan mengunduh dan meminjam buku selalu muncul "Verifikasi Perangkat Gagal". Padahal saya sudah menginstal aplikasi dari play store dan tidak memodifikasi perangkat atau aplikasinya. Gini amat nasib negara yang program pendidikan dan literasinya ga jadi program utama, mau akses buku digital susah, beli fisik juga harganya mahal :')
Date: 2026-05-28 22:05:35
A Google user: 1 stars
Review: kemarin saya pakai masih oke ok aja, hari ini 28 mei 26. saya ga bisa lanjut baca buku yg lagi dipinjam, notifnya suruh install dari playstore atau jangan modif hp. padahal saya install juga dari playstore dan hp saya ga pernah diutak atik apa-apanya aneh
Date: 2026-05-28 20:39:34
A Google user: 1 stars
Review: sering error, sebelum anggaran dipotong aja udh kacau aplg setelah anggarannya minim😂😂😂
Date: 2026-05-28 18:43:57
A Google user: 1 stars
Review: Baru download 2 minggu tiba-tiba muncul notif, perangkat tidak bisa diverifikasi. Tidak disarankan utk mendownload aplikasi ini.
Date: 2026-05-28 11:35:42
A Google user: 1 stars
Review: sebuah aplikasi yang mengagumkan dari pemerintah. berjalan dengan baik tanpa hambatan baik di IOS ataupun android. semoga amanah APBN kita berjalan sebagus ini terus ya. kalian orang pintar
Date: 2026-05-28 10:00:05
A Google user: 1 stars
Review: tidak bisa meminjam, karna verifikasi alat gagal
Date: 2026-05-28 09:43:16
A Google user: 3 stars
Review: Saya sudah menemukan buku bagus, lalu error. Kemrin error. hari ini error lagi. bulan lalu error lagi.
Date: 2026-05-28 07:15:53
A Google user: 3 stars
Review: selalu muncul notifikasi "verifikasi perangkat gagal" saat akan meminjam
Date: 2026-05-28 06:56:17
A Google user: 1 stars
Review: apps sering bermasalah
Date: 2026-05-28 06:39:19
A Google user: 1 stars
Review: padahal aplikasinya bagus untuk baca buku gratis, tapi belakangan sering terjadi masalah yg sama, verifikasi perangkat gagal, lagi dan lagi. padahal download langsung dari playstore. tolong benahi lagi karena sebenarnya aplikasi ini banyak membantu
Date: 2026-05-28 05:33:46
A Google user: 1 stars
Review: Aplikasi yg buruk
Date: 2026-05-28 04:35:04
A Google user: 3 stars
Review: Sering keluar keterangan "verifikasi perangkat gagal" sehingga tidak bisa melanjutkan membaca
Date: 2026-05-28 03:00:43
A Google user: 1 stars
Review: aplikasi ga bisa dipakai. uninstall aja deh
Date: 2026-05-28 02:38:30
A Google user: 3 stars
Review: apk nya sudah lumayan. tapi kadang-kadang saya tidak bisa meminjam buku atau melanjutkan bacaan saya di apk ini karen muncul pemberitahuan "perangkat anda tidak terdeteksi/terverifikasi". dan untuk koleksi bukunya tolong di perbanyak lagi
Date: 2026-05-28 01:40:35
A Google user: 1 stars
Review: buku sering ga bisa dibuka karena aplikasi tidak dapat memverifikasi perangkat (i don't even know what that means), udah restart device juga masih ga bisa dibuka bukunya. Tolong solusinya karena banyak buku di ipusnas yg ga ada versi cetaknya di toko2 buku
Date: 2026-05-25 01:03:56
A Google user: 3 stars
Review: Sebetulnya aplikasinya bagus karena menyediakan buku buku gratis bagi masyarakat, namun ada masalah yg harus dibenahi salah satunya kadang erornya aplikasi yg membuat pengguna kadang tidak bisa membaca buku yg sudah dipinjamnya ataupun tidak bisa meminjam buku. Semoga kekurangan kekurangan bisa segera dibehahi sehingga masyarakat bisa mengaksesnya dgn lancar...
Date: 2026-05-24 23:13:11
A Google user: 1 stars
Review: fix this app lah..
Date: 2026-05-24 22:06:35
A Google user: 1 stars
Review: aplikasi tidak dianggap resmi padahal download dari playstore. bangke
Date: 2026-05-24 21:56:07
A Google user: 5 stars
Review: Thanks for making this useful aplication, bravo!
Date: 2026-05-24 15:59:41
A Google user: 1 stars
Review: tolong pihak developer nya tingkatin lagi, ini bermasalah mulu dari sebelum sebelumnya. perangkat gagal lah, jaringan gada padahal lancar-lancar aja
Date: 2026-05-24 14:57:15
A Google user: 1 stars
Review: with updated version i can't download the book
Date: 2026-05-24 13:38:46
A Google user: 1 stars
Review: VERIFIKASI VERIFIKASI SAMPAH
Date: 2026-05-24 12:05:08
A Google user: 1 stars
Review: verifikasi selalu gagal... aplikasi apaan ini kalau ngga bisa digunakan..?
Date: 2026-05-24 07:30:36
A Google user: 1 stars
Review: ga bisa pinjem buku, selalu gagal verifikasi, pdhl sebelum2nya bisa pinjem berkali2.
Date: 2026-05-24 07:16:24
A Google user: 3 stars
Review: aplikasi nya ga jelas, verifikasi ulang terus sering bgt gangguan seperti ini
Date: 2026-05-24 06:52:42
A Google user: 1 stars
Review: verifikasi gagal, padahal saya download dari play store langsung, tim developer payah
Date: 2026-05-24 06:04:32
A Google user: 1 stars
Review: It's not work for my tablet, I use Lenovo Motorola tab and I can't borrow the books.
Date: 2026-05-24 04:48:54
A Google user: 1 stars
Review: Tidak bisa meminjam satu buku pun karena verifikasi perangkat gagal.
Date: 2026-05-24 04:07:50
A Google user: 4 stars
Review: I'm so glad to read more in this application during I had a lot of assignments and just for fun as my me time. Unfortunately, I can't entered in this application even I used my official account. Hopefully, it will be fixed immediately, therefore, I can have access again. Thank you.
Date: 2026-05-24 00:27:55
A Google user: 1 stars
Review: gagal verifikasi terus kalau mau baca atau pinjam buku
Date: 2026-05-23 23:52:57
A Google user: 2 stars
Review: kenapa sejak perbaikan malah sering error? gara2 efisiensi? 😭😭
Date: 2026-05-23 22:41:09
A Google user: 1 stars
Review: gabisa pinjem buku, verifikasi perangkat gagal, padahal hape ga diapa2in 🤷
Date: 2026-05-23 15:03:51
A Google user: 1 stars
Review: the app worked perfectly fine a week ago, but now it suddenly keeps saying that it cant verified my device and i have to download it at official playstore evertime i want to borrow the book.. very funny though, of course i download it from official store.. what does that even mean?? Please fix this issue ASAP!
Date: 2026-05-23 13:02:34
A Google user: 1 stars
Review: I can't borrow any book. The pop out message: verifikasi perangkat gagal. How on earth? I install it straight from play store
Date: 2026-05-23 12:56:26
A Google user: 5 stars
Review: please untuk developer perbaiki lagi aplikasinya. mungkin bisa secepatnya pleasee ada buku yang harus saya baca secepatnya. pleaseee, mungkin dengan kasih rate 5 bisaa segeraa diatasi. Ada kendala pada saat membaca buku. tulisannya "kami tidak dapat memverifikasi perangkat anda. pastikan anda menggunakan aplikasi resmi dari play store dan perangkat tidak dimodifikasi". pleasee segeraa diperbaikkii🙏
Date: 2026-05-23 12:30:34
A Google user: 1 stars
Review: pantesan banyak bintang 1. Error mulu.
Date: 2026-05-23 12:12:14
A Google user: 1 stars
Review: disappointed much eh? 2 hari lalu aku bisa loh pinjem buku ga ada masalah, skrng mau pinjem buku tiba tiba dibilang "verifikasi perangkat gagal" can't y'all do something about that..? I really want to read books by this app
Date: 2026-05-23 09:37:17
A Google user: 1 stars
Review: Gak bisa dipake
Date: 2026-05-23 08:21:12
A Google user: 1 stars
Review: iPusnas makin menyulitkan pengguna sendiri. Aplikasi dianggap “tidak resmi” hanya karena sumber instalasi berbeda, lalu dipaksa verifikasi berulang tanpa penjelasan jelas. Orang cuma mau baca buku, bukan diperiksa seperti pelaku kejahatan digital. Sistem keamanan terasa berlebihan dan pengalaman pengguna jadi buruk.
Date: 2026-05-23 07:31:31
A Google user: 1 stars
Review: aplikasi jelekkk
Date: 2026-05-23 06:53:16
A Google user: 1 stars
Review: sering eror maless
Date: 2026-05-23 06:28:55
A Google user: 2 stars
Review: kenapa pas aku mau baca malah ada tulisan "verifikasi perangkat gagal" padahal aku downloadnya di playstore dan bukan situs illegal. dan pas mau pinjam juga ada tulisan yg sama. app ini bagus buat baca krn nyaman tapi kenapa tiba2 ada gangguan ini? tolong developer buat benerin masalah ini
Date: 2026-05-23 04:41:47
A Google user: 1 stars
Review: the content is great but the UI/UX makes everything harder
Date: 2026-05-23 04:08:46
A Google user: 3 stars
Review: tolong di bagusin dong fitur nya, masa ga bisa di buka perangkat tidak terverifikasi katanya, padahal udah pakai aplikasi ini dari tahun 2022
Date: 2026-05-23 03:30:16
A Google user: 3 stars
Review: ni suka maen sulap apps nya, aplikasi ga diapa²in, perangkat ga diapa²in... kadang bisa bener sendiri, kdang error perangkat di.modifikasi.. sampe di fix nanti tak ubah reviewnya
Date: 2026-05-23 02:46:01
A Google user: 5 stars
Review: 28/04 Aplikasi iPusnas sudah bisa digunakan kembali. 22/05 Belum ada satu bulan~ sudah error lagi, verifikasi perangkat gagal wkwk.
Date: 2026-05-23 02:20:57
A Google user: 1 stars
Review: Why does there is notification 'We could not verify your device. Make sure you use the official application from Play Store and your device is not modified' appear when I try to continue reading? This hasn't happened before. I've been using good internet and my storage space is still good.
Date: 2026-05-23 00:29:00
A Google user: 1 stars
Review: Tak bisa baca buku. Tertulis aplikasi tidak asli dari playstore atau sudah dimodifikasi. Ya terus saya dapat aplikasi dari mana? Dan ngapain pula habisin waktu bajak aplikasi tak jelas macam ini?
Date: 2026-05-22 23:47:31
A Google user: 1 stars
Review: Padahal enak enak baca tapi tiba tiba banget "verifikasi gagal", mana bukunya udah nggak bisa dibaca offline lagi. hmm. gimana ya. servernya bermasalah mulu.
Date: 2026-05-22 23:34:01
A Google user: 5 stars
Review: membantu bgt nyari referensi untuk laporan praktikum, membaca buku buku lama yg gak jumpa lagi di toko buku edit 22 mei 2026 mengapa sering error padahal sudah update? lalu notifnya "pastikan menggunakan aplikasi resmi dari playstore", memangnya saya unduh darimana lagi?. saat ingin buka aplikasi sering bug dan tbtb log out. tolong dioptimalkan updatenya🙏🏼
Date: 2026-05-22 03:37:27
A Google user: 1 stars
Review: It’s very disappointing. After the update, when I try to borrow a book, the message “We cannot verify your device. Please make sure you are using the official app from the Play Store and that your device has not been modified.” appears. Even though I downloaded the app from the Play Store and my device has not been modified.
Date: 2026-05-22 03:26:48
A Google user: 1 stars
Review: trash app
Date: 2026-05-22 02:45:07
A Google user: 1 stars
Review: JELEK BANGET JELEKKKKKK
Date: 2026-05-22 02:12:19
A Google user: 1 stars
Review: instal rabu. dipakai baca tiap hari. dihari ketiga tiba-tiba aja bilang kesulitan verifikasi perangkat. kembalikan buku, edit profil busa. tapi pas klik Baca dibilang tidak dapat memverifikasi perangkat.
Date: 2026-05-22 01:37:07
A Google user: 5 stars
Review: Kecuali dari aplikasi yang kadang error dan beberapa kali tidak bisa membuka bacaan, koleksi menurut saya sudah cukup banyak dan sangat membantu utk orang yang terbatas koleksi buku fisik. semoga makin banyak koleksi buku yang ada 🙂‍↕️🙂‍↕️
Date: 2026-05-18 00:20:15
A Google user: 2 stars
Review: sebagai warga yang dengan dana minim, tapi ingin tetap membaca, saya mohon sekali, agar ada peningkatan di beberapa bagian aplikasi ini. karena jujur, saya tidak nyaman baca di sini, tidak seperti aplikasi lainnya yang sejenis. harap developer membaca ini. dan menghubungi saya agar keluhan saya tersampaikan.
Date: 2026-05-13 07:45:52
A Google user: 1 stars
Review: hp saya android 9 mendadak sudah tidak bisa digunakan untuk mengakses ipusnas :( padahal digilib lain masih bisa. sedih bgt gini amat pengen baca gratis secara legal terkendala device
Date: 2026-05-09 22:43:42
A Google user: 2 stars
Review: update terbaru 9 mei 2026 alangkah susahnya ya mau baca buku aja selalu verifikasi perangkat gagal, susahnya negri ini menyediakan utk rakyatnya membaca aja dipersulit nasib nasib
Date: 2026-05-09 12:23:06
A Google user: 5 stars
Review: Cant even log in
Date: 2026-05-08 13:50:34
A Google user: 1 stars
Review: aplikasinya makin lama makin jelek aja. dari yg awalny sering ngelag, eror gk bisa minjem, gk bisa dibuka aplikasinya, dan sekarang buka aplikasiny harus punya data🙂 hahaha lucu ya, padahal harusnya pemerintah buat aplikasi baca buku gratis gini biar banyak orang yg tertarik buat baca karena mudah diakses, eh sekarang malah dipersulit. takut bgt apa punya generasi yg suka literasi? padahal salah satu kelebihannya bisa dibaca offline karena gk semua org punya banyak data internet😮‍💨
Date: 2026-05-08 12:30:46
A Google user: 3 stars

In [10]:
import pandas as pd
df=pd.DataFrame(result)
df.to_csv('ipusnasdata_raw.csv', index=False)

In [11]:
df

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,5c4937e1-8a6f-46f3-85b5-d8d51a4871eb,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,novel lockwood and co nya lengkapin plissss,4,0,2.1.4,2026-06-26 01:19:13,None,NaT,2.1.4
1,2664d873-11c9-4543-9218-82610b6e333e,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,"tidak bisa membuka buku yang sudah dipinjam, t...",1,1,2.1.4,2026-06-25 08:05:43,None,NaT,2.1.4
2,b0dcd850-ef00-43da-b52a-ebcfea80e4dc,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,Kenapa saya tidak bisa membaca buku yang sudah...,1,1,2.1.4,2026-06-25 07:43:20,None,NaT,2.1.4
3,4eddc1c4-b7fb-463f-8fea-e29e3338219d,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,Tolong dibenerin lagi apk nya karena saya mau ...,2,0,None,2026-06-25 07:34:18,None,NaT,None
4,a0d91fe5-75ed-4b11-a2f8-0ab33d5f8639,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,Tidak mampu memverifikasi perangkat.,1,0,2.1.4,2026-06-25 06:21:29,None,NaT,2.1.4
...,...,...,...,...,...,...,...,...,...,...,...
3995,f244f517-719e-40ef-8614-0d166c762c59,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,Saya suka aplikasi ini. Mmg pernah bbrp kali m...,5,0,1.4.7,2020-06-26 11:10:34,Hallo Ratna! Kami mohon maaf atas ketidaknyama...,2019-11-04 02:00:30,1.4.7
3996,08c2da7e-065f-4ce8-8d28-c4c5cf5d9dcb,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,Aplikasi yg sangat bagus menurut saya. Saya bi...,5,0,1.4.7,2020-06-25 08:15:23,Hallo Brillian Tobibi! Terima kasih sudah memb...,2020-06-25 08:39:08,1.4.7
3997,10623d71-fd0f-4768-b63b-dd69889553fe,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,it keep saying problem occured everytime i lau...,5,0,1.4.7,2020-06-24 23:32:09,None,NaT,1.4.7
3998,68d9f22c-293c-4fa2-b4e8-cf48287ac1d5,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,"Aplikasi berjalan dg baik, banyak koleksi buku...",5,0,1.4.6,2020-06-24 13:06:42,Hallo Punto! Terima kasih sudah memberikan ula...,2020-06-25 08:37:46,1.4.6
3999,6397fdde-4f06-41b6-bde2-223bf3006142,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,Eror parah,1,0,1.4.7,2020-06-24 12:25:32,Kami mohon maaf atas kendala dan ketidaknyaman...,2020-06-25 04:49:47,1.4.7

In [12]:
df['at'] = pd.to_datetime(df['at'])
start = pd.to_datetime("2021-01-01")
end   = pd.to_datetime("2026-05-16")
mask = (df['at'] >= start) & (df['at'] <= end)
filtered = df[mask]

filtered[['userName','score','content','at']]

,userName,score,content,at
91,A Google user,2,"sebagai warga yang dengan dana minim, tapi ing...",2026-05-13 07:45:52
92,A Google user,1,hp saya android 9 mendadak sudah tidak bisa di...,2026-05-09 22:43:42
93,A Google user,2,update terbaru 9 mei 2026 alangkah susahnya ya...,2026-05-09 12:23:06
94,A Google user,5,Cant even log in,2026-05-08 13:50:34
95,A Google user,1,aplikasinya makin lama makin jelek aja. dari y...,2026-05-08 12:30:46
...,...,...,...,...
3600,A Google user,2,"Saya kira filter pencariannya kurang variatif,...",2021-01-03 05:57:05
3601,A Google user,5,Lagi maintenance ya?,2021-01-03 01:16:17
3602,A Google user,2,"i can't open this app.. -,-",2021-01-02 18:55:19
3603,A Google user,3,Saya cukup puas dengan aplikasi perpustakaan i...,2021-01-02 18:06:19
3604,A Google user,3,Tidak bisa menggunakan fungsi search. Mohon di...,2021-01-02 14:47:16

In [13]:
filtered.to_csv("ipusnasdata.csv", index=False)

In [14]:
from google.colab import files
files.download('ipusnasdata.csv')